version: '3.8'

services:
  backend:
    build: ./backend
    container_name: stock-prediction-backend
    ports:
      - "5000:5000"
    environment:
      - API_KEY=9VV82SEKR0JTH02Q
    networks:
      - stock-net

  frontend:
    build: ./frontend
    container_name: stock-prediction-frontend
    ports:
      - "3000:3000"
    networks:
      - stock-net

  db:
    image: postgres:latest
    container_name: stock-db
    environment:
      POSTGRES_DB: stockdb
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - stock-net

networks:
  stock-net:
    driver: bridge
